{
 "title": "Postgres Autovacuum",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(pg_up, namespace)" } },
   {
    "name": "job",
    "query": {
     "query": "label_values(pg_up{namespace=\"$namespace\"}, job)"
    }
   },
   {
    "name": "datname",
    "query": {
     "query": "label_values(pg_stat_database_stats_reset{job=\"$job\", namespace=\"$namespace\"}, datname)\t"
    }
   },
   {
    "name": "relname",
    "query": {
     "query": "label_values(pg_stat_user_tables_idx_scan{job=\"$job\", namespace=\"$namespace\", datname=\"$datname\"}, relname)\t"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{namespace=\"$namespace\",job=\"$job\"} * 1000"
    },
    {}
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"$job\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 13, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{job=\"$job\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{job=\"$job\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Disk space used by database",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg_database_size_bytes{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "AutoVacuum Count by table",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_user_tables_autovacuum_count",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Dead tuples by table",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pg_stat_user_tables_n_dead_tup", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deleted tuples irate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (irate(pg_stat_user_tables_n_tup_del{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[5m]))",
     "legendFormat": "{{relname}}"
    },
    {
     "expr": "sum by (relname) (pg_stat_user_tables_autovacuum_count{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Vacuum_count {{relname}}"
    }
   ]
  },
  {
   "title": "Inserted tuples irate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (irate(pg_stat_user_tables_n_tup_ins{namespace=\"$namespace\",job=\"$job\",datname=~\"$datname\",relname=~\"$relname\"}[5m]))",
     "legendFormat": "{{relname}}"
    },
    {
     "expr": "sum by (relname) (pg_stat_user_tables_autovacuum_count{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"})",
     "legendFormat": "Vacuum_count {{relname}}"
    }
   ]
  },
  {
   "title": "Updated tuples irate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (irate(pg_stat_user_tables_n_tup_upd{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[5m]))",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Last Autovacuum Finish time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - pg_stat_user_tables_last_autovacuum{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Autovacuum changes last hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (increase(pg_stat_user_tables_autovacuum_count{namespace=\"$namespace\",job=\"$job\",datname=\"$datname\",relname=~\"$relname\"}[1h]))",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "timeseries",
   "description": "Current number of slow queries",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(pg_slow_queries{namespace=\"$namespace\"})\n",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Checkpoint ",
   "type": "timeseries",
   "description": "If checkpoint durations are high, it might mean I/O resources are being heavily utilized, potentially delaying autovacuum.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(checkpoint_time_value[5m])\n"
    }
   ]
  },
  {
   "title": "Buffers Allocated",
   "type": "timeseries",
   "description": "A high rate of buffer allocations might indicate frequent modifications (inserts, updates, or deletes), which could create dead tuples faster than autovacuum can clean them up.",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "buffers_alloc_value{namespace=\"$namespace\",job=\"$job\"}\n"
    }
   ]
  }
 ]
}